# Generated by Django 5.2.14 on 2026-06-11 06:11

import django.contrib.postgres.indexes
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('icon', models.CharField(help_text='Frontend icon identifier', max_length=50)),
                ('is_system_default', models.BooleanField(default=False, help_text='Prevents deletion of default modules')),
                ('is_hidden', models.BooleanField(default=False)),
                ('display_order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CategoryField',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('field_type', models.CharField(choices=[('TEXT', 'Short Text'), ('LONG_TEXT', 'Long Text'), ('NUMBER', 'Number'), ('DROPDOWN', 'Select Option'), ('COLOR_STATUS', 'Status Label'), ('EMPLOYEE', 'Employee Lookup'), ('LOCATION', 'Location Lookup')], max_length=20)),
                ('is_required', models.BooleanField(default=False)),
                ('is_locked', models.BooleanField(default=False, help_text='System fields cannot be modified/deleted')),
                ('options_metadata', models.JSONField(blank=True, default=list, help_text='JSON array for dropdown/color options')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='assets.assetcategory')),
            ],
            options={
                'unique_together': {('category', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('internal_tag', models.CharField(max_length=50, unique=True)),
                ('dynamic_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_assets', to='employees.employee')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='assets.assetcategory')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='assets.location')),
            ],
            options={
                'permissions': [('view_global_inventory', 'Can view assets across all locations'), ('manage_global_inventory', 'Can manage assets across all locations')],
                'indexes': [models.Index(fields=['location', 'category'], name='assets_asse_locatio_24d511_idx'), models.Index(fields=['internal_tag'], name='assets_asse_interna_68b008_idx'), django.contrib.postgres.indexes.GinIndex(fields=['dynamic_data'], name='assets_asse_dynamic_67f778_gin')],
            },
        ),
    ]
