# Generated by Django 5.2.14

from django.db import migrations
import uuid

def seed_categories(apps, schema_editor):
    AssetCategory = apps.get_model('assets', 'AssetCategory')
    CategoryField = apps.get_model('assets', 'CategoryField')

    # Diccionarios de estados comunes (Homologados Label = Value)
    device_status = [
        {"label": "In Use", "value": "In Use", "color": "Green"},
        {"label": "Stored", "value": "Stored", "color": "Gray"},
        {"label": "In Delivery", "value": "In Delivery", "color": "Purple"},
        {"label": "Damaged", "value": "Damaged", "color": "Yellow"},
        {"label": "Stolen", "value": "Stolen", "color": "Red"},
        {"label": "Missing", "value": "Missing", "color": "Red"},
    ]

    infra_status = [
        {"label": "Active", "value": "Active", "color": "Green"},
        {"label": "Stored", "value": "Stored", "color": "Gray"},
        {"label": "Damaged", "value": "Damaged", "color": "Yellow"},
        {"label": "Stolen", "value": "Stolen", "color": "Red"},
        {"label": "Missing", "value": "Missing", "color": "Red"},
    ]

    license_status = [
        {"label": "In Use", "value": "In Use", "color": "Green"},
        {"label": "Not in Use", "value": "Not in Use", "color": "Gray"},
    ]

    # Estructura Maestra del SaaS (Homologada)
    categories_data = [
        {
            "name": "PCs / Laptops",
            "icon": "desktop-pc",
            "order": 10,
            "fields": [
                {"name": "Type", "type": "DROPDOWN", "req": True, "locked": True, "opts": [{"label": "Desktop Computer", "value": "Desktop Computer"}, {"label": "Laptop", "value": "Laptop"}]},
                {"name": "Status", "type": "COLOR_STATUS", "req": True, "locked": True, "opts": device_status},
                {"name": "Assigned To", "type": "EMPLOYEE", "req": True, "locked": False, "opts": []},
                {"name": "Location", "type": "LOCATION", "req": True, "locked": False, "opts": []},
                {"name": "Model", "type": "TEXT", "req": False, "locked": False, "opts": []},
                {"name": "Observations", "type": "LONG_TEXT", "req": False, "locked": False, "opts": []},
            ]
        },
        {
            "name": "Mobile Devices",
            "icon": "device-phone-mobile",
            "order": 20,
            "fields": [
                {"name": "Type", "type": "DROPDOWN", "req": True, "locked": True, "opts": [{"label": "Corporate Phone", "value": "Corporate Phone"}, {"label": "Tablet", "value": "Tablet"}]},
                {"name": "Status", "type": "COLOR_STATUS", "req": True, "locked": True, "opts": device_status},
                {"name": "Assigned To", "type": "EMPLOYEE", "req": True, "locked": False, "opts": []},
                {"name": "Location", "type": "LOCATION", "req": True, "locked": False, "opts": []},
                {"name": "Model", "type": "TEXT", "req": False, "locked": False, "opts": []},
                {"name": "Observations", "type": "LONG_TEXT", "req": False, "locked": False, "opts": []},
            ]
        },
        {
            "name": "IT Infrastructure",
            "icon": "server",
            "order": 30,
            "fields": [
                {"name": "Type", "type": "DROPDOWN", "req": True, "locked": True, "opts": [{"label": "IPv4 Router", "value": "IPv4 Router"}, {"label": "IPv6 Router", "value": "IPv6 Router"}, {"label": "Dual-Stack Router", "value": "Dual-Stack Router"}, {"label": "Wifi Repeater", "value": "Wifi Repeater"}]},
                {"name": "Status", "type": "COLOR_STATUS", "req": True, "locked": True, "opts": infra_status},
                {"name": "Location", "type": "LOCATION", "req": True, "locked": False, "opts": []},
                {"name": "Model", "type": "TEXT", "req": False, "locked": False, "opts": []},
                {"name": "Observations", "type": "LONG_TEXT", "req": False, "locked": False, "opts": []},
            ]
        },
        {
            "name": "Printers",
            "icon": "printer",
            "order": 40,
            "fields": [
                {"name": "Type", "type": "DROPDOWN", "req": True, "locked": True, "opts": [{"label": "Canon Printer", "value": "Canon Printer"}, {"label": "Xerox Printer", "value": "Xerox Printer"}, {"label": "Kyocera Printer", "value": "Kyocera Printer"}]},
                {"name": "Status", "type": "COLOR_STATUS", "req": True, "locked": True, "opts": infra_status},
                {"name": "Location", "type": "LOCATION", "req": True, "locked": False, "opts": []},
                {"name": "Model", "type": "TEXT", "req": False, "locked": False, "opts": []},
                {"name": "Observations", "type": "LONG_TEXT", "req": False, "locked": False, "opts": []},
            ]
        },
        {
            "name": "Security Cameras",
            "icon": "video-camera",
            "order": 50,
            "fields": [
                {"name": "Type", "type": "DROPDOWN", "req": True, "locked": True, "opts": [{"label": "Vivint Camera", "value": "Vivint Camera"}]},
                {"name": "Status", "type": "COLOR_STATUS", "req": True, "locked": True, "opts": infra_status},
                {"name": "Location", "type": "LOCATION", "req": True, "locked": False, "opts": []},
                {"name": "Room", "type": "TEXT", "req": False, "locked": False, "opts": []},
                {"name": "Model", "type": "TEXT", "req": False, "locked": False, "opts": []},
                {"name": "Observations", "type": "LONG_TEXT", "req": False, "locked": False, "opts": []},
            ]
        },
        {
            "name": "Virtual Licenses",
            "icon": "key",
            "order": 60,
            "fields": [
                {"name": "Software", "type": "DROPDOWN", "req": True, "locked": True, "opts": [{"label": "Microsoft 365 E3", "value": "Microsoft 365 E3"}, {"label": "Microsoft Business Basic", "value": "Microsoft Business Basic"}, {"label": "Microsoft Business Standard", "value": "Microsoft Business Standard"}, {"label": "Slack Standard User", "value": "Slack Standard User"}, {"label": "Hubstaff User", "value": "Hubstaff User"}]},
                {"name": "Status", "type": "COLOR_STATUS", "req": True, "locked": True, "opts": license_status},
                {"name": "Assigned To", "type": "EMPLOYEE", "req": True, "locked": False, "opts": []},
                {"name": "Observations", "type": "LONG_TEXT", "req": False, "locked": False, "opts": []},
            ]
        }
    ]

    for cat_data in categories_data:
        # 1. Crear Categoría (System Default)
        category = AssetCategory.objects.create(
            id=uuid.uuid4(),
            name=cat_data["name"],
            icon=cat_data["icon"],
            is_system_default=True,
            is_hidden=False,
            display_order=cat_data["order"]
        )

        # 2. Crear los campos (CategoryFields) para la categoría
        for field_data in cat_data["fields"]:
            CategoryField.objects.create(
                id=uuid.uuid4(),
                category=category,
                name=field_data["name"],
                field_type=field_data["type"],
                is_required=field_data["req"],
                is_locked=field_data["locked"],
                options_metadata=field_data["opts"]
            )

def reverse_seed(apps, schema_editor):
    AssetCategory = apps.get_model('assets', 'AssetCategory')
    # Permite deshacer la migración limpiando las categorías por defecto
    AssetCategory.objects.filter(is_system_default=True).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed_categories, reverse_seed),
    ]