# Generated by Django 5.2.14 on 2026-06-20 08:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_seed_default_categories'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTablePreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('columns_config', models.JSONField(default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_preferences', to='assets.assetcategory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='table_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'asset_user_table_preferences',
                'unique_together': {('user', 'category')},
            },
        ),
    ]
