# Generated by Django 5.2.14 on 2026-07-01 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_usertablepreference'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoryfield',
            options={'ordering': ['-is_locked', 'display_order']},
        ),
        migrations.AddField(
            model_name='categoryfield',
            name='display_order',
            field=models.IntegerField(default=0),
        ),
    ]
