# Generated by Django 5.2.14 on 2026-07-17 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='entity_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
